export const mockJobs = [
  {
    id: '1',
    title: 'Full Stack Blockchain Developer Needed for DeFi Platform',
    description: 'We are looking for an experienced blockchain developer to help build a new DeFi platform. The project involves creating smart contracts, integrating with existing DeFi protocols, and building a responsive front-end.',
    client: 'DeFi Innovations',
    budget: 5000,
    paymentType: 'fixed',
    duration: '1-3 months',
    postedDate: '2025-04-01',
    skills: ['Solidity', 'React', 'Web3.js', 'Ethereum', 'Smart Contracts'],
    category: 'Smart Contract Development',
    experienceLevel: 'Expert'
  },
  {
    id: '2',
    title: 'NFT Marketplace Designer & Developer',
    description: 'We need a talented designer and developer to create a custom NFT marketplace for digital art. The platform should support minting, buying, selling, and auctioning NFTs.',
    client: 'ArtChain Collective',
    budget: 8000,
    paymentType: 'fixed',
    duration: '2-4 months',
    postedDate: '2025-04-05',
    skills: ['NFT', 'Solidity', 'React', 'UI/UX Design', 'Smart Contracts'],
    category: 'Smart Contract Development',
    experienceLevel: 'Expert'
  },
  {
    id: '3',
    title: 'Web3 Front-End Developer for Crypto Exchange',
    description: 'Looking for a front-end developer with experience in Web3 integration to help redesign our cryptocurrency exchange interface. Must be familiar with wallets integration and blockchain data fetching.',
    client: 'SecureExchange',
    budget: 70,
    paymentType: 'hourly',
    duration: '3-6 months',
    postedDate: '2025-04-07',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Web3.js', 'UI/UX'],
    category: 'Web Development',
    experienceLevel: 'Intermediate'
  },
  {
    id: '4',
    title: 'Smart Contract Auditor for New Token Launch',
    description: 'We need a security expert to audit our ERC-20 token and crowdsale smart contracts before launching. Must have experience in identifying vulnerabilities and suggesting optimizations.',
    client: 'TokenLaunch Inc',
    budget: 3000,
    paymentType: 'fixed',
    duration: '2-3 weeks',
    postedDate: '2025-04-09',
    skills: ['Smart Contract Auditing', 'Solidity', 'Security', 'ERC-20', 'Ethereum'],
    category: 'Smart Contract Development',
    experienceLevel: 'Expert'
  },
  {
    id: '5',
    title: 'Blockchain Documentation Writer',
    description: 'We need a technical writer to create comprehensive documentation for our blockchain protocol. The ideal candidate has experience explaining complex blockchain concepts in simple terms.',
    client: 'ChainDocs',
    budget: 2000,
    paymentType: 'fixed',
    duration: '1-2 months',
    postedDate: '2025-04-10',
    skills: ['Technical Writing', 'Blockchain', 'Documentation', 'Markdown', 'Research'],
    category: 'Writing & Translation',
    experienceLevel: 'Intermediate'
  },
  {
    id: '6',
    title: 'Mobile App Developer for Crypto Wallet',
    description: 'Seeking a mobile developer to build a cross-platform cryptocurrency wallet app. The app should support multiple blockchains and include features like transaction history, price tracking, and biometric security.',
    client: 'MultiChain Wallet',
    budget: 6500,
    paymentType: 'fixed',
    duration: '2-3 months',
    postedDate: '2025-04-12',
    skills: ['React Native', 'Mobile Development', 'Blockchain', 'API Integration', 'Security'],
    category: 'Mobile Development',
    experienceLevel: 'Intermediate'
  },
  {
    id: '7',
    title: 'Blockchain Marketing Specialist',
    description: 'We are looking for a marketing specialist with experience in the blockchain and cryptocurrency space to help promote our new decentralized application. Tasks include content creation, social media management, and community engagement.',
    client: 'DAppMarketing',
    budget: 50,
    paymentType: 'hourly',
    duration: 'Ongoing',
    postedDate: '2025-04-15',
    skills: ['Digital Marketing', 'Social Media', 'Content Creation', 'Blockchain', 'Community Management'],
    category: 'Marketing',
    experienceLevel: 'Intermediate'
  },
  {
    id: '8',
    title: 'Full Stack Developer for Web3 Social Platform',
    description: 'We are building a decentralized social media platform and need a full stack developer to help with both front-end and back-end development. Experience with blockchain integration is required.',
    client: 'DecentralSocial',
    budget: 7000,
    paymentType: 'fixed',
    duration: '3-5 months',
    postedDate: '2025-04-16',
    skills: ['React', 'Node.js', 'MongoDB', 'Web3.js', 'IPFS'],
    category: 'Web Development',
    experienceLevel: 'Expert'
  },
  {
    id: '9',
    title: 'Blockchain Data Analyst',
    description: 'Looking for a data analyst to help us gather and interpret on-chain data for market research. The ideal candidate has experience with blockchain explorers and data visualization tools.',
    client: 'Chain Insights',
    budget: 60,
    paymentType: 'hourly',
    duration: 'Ongoing',
    postedDate: '2025-04-18',
    skills: ['Data Analysis', 'Python', 'SQL', 'Data Visualization', 'Blockchain'],
    category: 'Data Science & Analytics',
    experienceLevel: 'Intermediate'
  },
  {
    id: '10',
    title: 'UI/UX Designer for DeFi Dashboard',
    description: 'We need a creative UI/UX designer to redesign our DeFi dashboard. The design should be intuitive, modern, and help users easily track their investments across multiple protocols.',
    client: 'DeFi Tracker',
    budget: 4000,
    paymentType: 'fixed',
    duration: '1-2 months',
    postedDate: '2025-04-20',
    skills: ['UI/UX Design', 'Figma', 'User Research', 'Wireframing', 'Prototyping'],
    category: 'Design & Creative',
    experienceLevel: 'Intermediate'
  },
  {
    id: '11',
    title: 'Polygon Smart Contract Developer',
    description: 'We are developing a new Play-to-Earn game on Polygon and need a smart contract developer to create the in-game economy and NFT integration. Experience with ERC-721 and ERC-1155 standards is required.',
    client: 'PolyPlay Studios',
    budget: 4500,
    paymentType: 'fixed',
    duration: '1-3 months',
    postedDate: '2025-04-22',
    skills: ['Polygon', 'Solidity', 'NFT', 'Gaming', 'Smart Contracts'],
    category: 'Smart Contract Development',
    experienceLevel: 'Intermediate'
  },
  {
    id: '12',
    title: 'Customer Support Specialist for Crypto Exchange',
    description: 'We are looking for a customer support specialist to help our users with account-related issues, transaction problems, and general inquiries. The ideal candidate has experience in cryptocurrency and excellent communication skills.',
    client: 'SecureExchange',
    budget: 25,
    paymentType: 'hourly',
    duration: 'Ongoing',
    postedDate: '2025-04-25',
    skills: ['Customer Service', 'Communication', 'Problem Solving', 'Cryptocurrency', 'Zendesk'],
    category: 'Customer Service',
    experienceLevel: 'Entry'
  }
];